### ISSUE TITLE
Please fix bugtracker link

### ISSUE THREAD

**Issue by pcav** [DomenicoM92/Nuclear-Energy-Plant-Radiations-#4]
currently broken.
Thanks.

**Comment by DomenicoM92** [comment]
Hi, I've add this repo github link, is it right?

**Comment by pcav** [comment]
not, it should be https://github.com/DomenicoM92/Nuclear-Energy-Plant-Radiations-/issues/
Cheers.

**Comment by DomenicoM92** [comment]
Thanks so much!
