### ISSUE TITLE
Please improve About and Description

### ISSUE THREAD

**Issue by pcav** [DomenicoM92/Nuclear-Energy-Plant-Radiations-#6]
Ideally the description should be a short sentence, and the about a full description.
Thanks.

**Comment by DomenicoM92** [comment]
Hi, I've done.

**Comment by pcav** [comment]
The description now does not help a prospective user to understand why he should install it. I can suggest something like "Visualize all nuclear energy plant in the world" or similar.

**Comment by DomenicoM92** [comment]
Ok, I update it.
