### ISSUE TITLE
Some more info about data shown

### ISSUE THREAD

**Issue by rduivenvoorde** [DomenicoM92/Nuclear-Energy-Plant-Radiations-#7]
Hi, thanks for the plugin. Nice to see mqtt is flowing into QGIS ;-)

As I'm sometimes doing work in this field, I have some questions of which I think it would be good to put the info in the plugin, description or a separate info page.

But I wonder what I see...

![Screenshot-20200107135755-470x339](https://user-images.githubusercontent.com/731673/71897058-b52fa080-3155-11ea-84a1-7ea76491d8da.png)

Do you have any unit which is shown there (58.00 kilograms/watt's/microSievert per hour/gray/?)

Which datasource is used? Looking into the code, you use some free mqtt service?

But I see you publish random values between 0 and 200: ???

https://github.com/DomenicoM92/Nuclear-Energy-Plant-Radiations-/blob/master/mqttPublisher.py#L33-L38

And do you then subscribe to the same topic?

https://github.com/DomenicoM92/Nuclear-Energy-Plant-Radiations-/blob/master/mqttSubscriber.py#L39

Same in plugin:

https://github.com/DomenicoM92/Nuclear-Energy-Plant-Radiations-/blob/master/nuclear_energy_plant_radiation_module.py#L246

So I really wonder if I see true data or just some random values.
IF it is random data, I think you should make your plugin 'experimental' for now, as this could potentially upset/worry people.
ELSE: please provide thorough docs about WHAT people are seeing and what the sources are from you r (live?) data.

Second: as you are 'data'-people? Are you sure a heatmap is the best solution for this kind of data? As now in area's with a lot of plants it quickly becomes 'yellow' with me?

Thanks!

**Comment by DomenicoM92** [comment]
Hi, for now it use fake radiation, it simulate radiation that comes from sensors. We've used the Cloud mqtt for do this, the used datasets is in the datasets folder (it is a open dataset). I'll change in experimental, thanks so much.

**Comment by DomenicoM92** [comment]
In order to clarify the radiation data I've explained, moreover, the type of date in readme and in the description it.
